#pragma once

namespace linweb {

#ifdef WESTON_PLATFORM

const char *vs_color_src =
    "attribute vec2 aPos;\n"
    "attribute vec4 aColor;\n"
    "attribute vec2 aUV;\n"
    "uniform mat4 uProj;\n"
    "uniform mat4 uModel;\n"
    "varying vec4 vColor;\n"
    "varying vec2 vUV;\n"
    "void main(){ vColor=aColor; vUV=aUV; gl_Position=uProj*uModel*vec4(aPos,0.0,1.0); }\n";

const char *fs_color_src =
    "precision mediump float;\n"
    "varying vec4 vColor;\n"
    "varying vec2 vUV;\n"
    "uniform vec2 uSize;\n"
    "uniform float uRadius;\n"
    "uniform float uBlur;\n"
    "uniform float uInvert;\n"
    "uniform int uGradType;\n"
    "uniform vec4 uGradC1;\n"
    "uniform vec4 uGradC2;\n"
    "uniform vec4 uGradC3;\n"
    "uniform vec4 uGradC4;\n"
    "uniform float uGradS1;\n"
    "uniform float uGradS2;\n"
    "uniform float uGradS3;\n"
    "uniform float uGradS4;\n"
    "uniform int uGradCount;\n"
    "uniform float uGradAngle;\n"
    "uniform float uBorderWidth;\n"
    "float sdRoundRect(vec2 p, vec2 b, float r) {\n"
    "  vec2 d = abs(p) - b + vec2(r);\n"
    "  return min(max(d.x, d.y), 0.0) + length(max(d, 0.0)) - r;\n"
    "}\n"
    "vec4 gradient_color(float t) {\n"
    "  if (uGradCount <= 2) return mix(uGradC1, uGradC2, clamp((t - uGradS1) / (uGradS2 - uGradS1), 0.0, 1.0));\n"
    "  if (t <= uGradS2) return mix(uGradC1, uGradC2, clamp((t - uGradS1) / (uGradS2 - uGradS1), 0.0, 1.0));\n"
    "  if (uGradCount == 3) return mix(uGradC2, uGradC3, clamp((t - uGradS2) / (uGradS3 - uGradS2), 0.0, 1.0));\n"
    "  if (t <= uGradS3) return mix(uGradC2, uGradC3, clamp((t - uGradS2) / (uGradS3 - uGradS2), 0.0, 1.0));\n"
    "  return mix(uGradC3, uGradC4, clamp((t - uGradS3) / (uGradS4 - uGradS3), 0.0, 1.0));\n"
    "}\n"
    "void main() {\n"
    "  vec2 halfSize = uSize * 0.5;\n"
    "  vec2 p = (vUV - 0.5) * uSize;\n"
    "  float dist = sdRoundRect(p, halfSize, uRadius);\n"
    "  float alpha = 0.0;\n"
    "  if (uBorderWidth > 0.0) {\n"
    "    vec2 innerHalf = halfSize - vec2(uBorderWidth);\n"
    "    float innerRadius = max(0.0, uRadius - uBorderWidth);\n"
    "    float innerDist = sdRoundRect(p, innerHalf, innerRadius);\n"
    "    float outerAlpha = 1.0 - smoothstep(-1.0, 1.0, dist);\n"
    "    float innerAlpha = 1.0 - smoothstep(-1.0, 1.0, innerDist);\n"
    "    alpha = outerAlpha - innerAlpha;\n"
    "  } else if (uBlur > 0.1) {\n"
    "    alpha = 1.0 - smoothstep(-uBlur * 0.5, uBlur * 1.5, dist);\n"
    "  } else {\n"
    "    alpha = 1.0 - smoothstep(-1.0, 1.0, dist);\n"
    "  }\n"
    "  vec4 finalColor = vColor;\n"
    "  if (uGradType == 1) {\n"
    "    float rad = (90.0 - uGradAngle) * 0.01745329;\n"
    "    vec2 dir = vec2(cos(rad), -sin(rad));\n"
    "    float t = dot(vUV - 0.5, dir) + 0.5;\n"
    "    finalColor = gradient_color(clamp(t, 0.0, 1.0));\n"
    "  } else if (uGradType == 2) {\n"
    "    float t = length(vUV - 0.5) * 2.0;\n"
    "    finalColor = gradient_color(clamp(t, 0.0, 1.0));\n"
    "  }\n"
    "  vec3 rgb = mix(finalColor.rgb, 1.0 - finalColor.rgb, uInvert);\n"
    "  gl_FragColor = vec4(rgb, finalColor.a * alpha);\n"
    "}\n";

const char *vs_text_src =
    "attribute vec2 aPos;\n"
    "attribute vec2 aUV;\n"
    "attribute vec4 aColor;\n"
    "uniform mat4 uProj;\n"
    "uniform mat4 uModel;\n"
    "varying vec2 vUV;\n"
    "varying vec4 vColor;\n"
    "void main(){ vUV=aUV; vColor=aColor; gl_Position=uProj*uModel*vec4(aPos,0.0,1.0); }\n";

const char *fs_text_src =
    "precision mediump float;\n"
    "uniform sampler2D uTex;\n"
    "uniform float uBlur;\n"
    "uniform float uInvert;\n"
    "varying vec2 vUV;\n"
    "varying vec4 vColor;\n"
    "void main() {\n"
    "  float a = texture2D(uTex, vUV).a;\n"
    "  if (uBlur > 0.1) {\n"
    "    float o = uBlur * 0.0015;\n"
    "    float sum = a * 4.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(o, 0.0)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV - vec2(o, 0.0)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(0.0, o)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV - vec2(0.0, o)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(o, o)).a * 1.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(o, -o)).a * 1.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(-o, o)).a * 1.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(-o, -o)).a * 1.0;\n"
    "    a = sum / 16.0;\n"
    "  }\n"
    "  vec3 color = mix(vColor.rgb, 1.0 - vColor.rgb, uInvert);\n"
    "  gl_FragColor = vec4(color, vColor.a * a);\n"
    "}\n";

const char *vs_image_src =
    "attribute vec2 aPos;\n"
    "attribute vec2 aUV;\n"
    "uniform mat4 uProj;\n"
    "uniform mat4 uModel;\n"
    "varying vec2 vUV;\n"
    "void main(){ vUV=aUV; gl_Position=uProj*uModel*vec4(aPos,0.0,1.0); }\n";

const char *fs_image_src =
    "precision mediump float;\n"
    "uniform sampler2D uTex;\n"
    "uniform vec2 uSize;\n"
    "uniform float uRadius;\n"
    "uniform vec2 uShadowOffset;\n"
    "uniform float uShadowBlur;\n"
    "uniform vec4 uShadowColor;\n"
    "varying vec2 vUV;\n"
    "float sdRoundRect(vec2 p, vec2 b, float r) {\n"
    "  vec2 d = abs(p) - b + vec2(r);\n"
    "  return min(max(d.x, d.y), 0.0) + length(max(d, 0.0)) - r;\n"
    "}\n"
    "float sampleAlpha(vec2 uv) {\n"
    "  return texture2D(uTex, uv).a;\n"
    "}\n"
    "void main() {\n"
    "  vec4 texColor = texture2D(uTex, vUV);\n"
    "  vec4 finalColor = texColor;\n"
    "  if (uShadowBlur > 0.0 || uShadowOffset.x != 0.0 || uShadowOffset.y != 0.0) {\n"
    "    float o = uShadowBlur * 0.003;\n"
    "    vec2 suv = vUV - uShadowOffset;\n"
    "    float sa = sampleAlpha(suv) * 4.0;\n"
    "    sa += sampleAlpha(suv + vec2(o, 0.0)) * 2.0;\n"
    "    sa += sampleAlpha(suv - vec2(o, 0.0)) * 2.0;\n"
    "    sa += sampleAlpha(suv + vec2(0.0, o)) * 2.0;\n"
    "    sa += sampleAlpha(suv - vec2(0.0, o)) * 2.0;\n"
    "    sa += sampleAlpha(suv + vec2(o, o)) * 1.0;\n"
    "    sa += sampleAlpha(suv + vec2(o, -o)) * 1.0;\n"
    "    sa += sampleAlpha(suv + vec2(-o, o)) * 1.0;\n"
    "    sa += sampleAlpha(suv + vec2(-o, -o)) * 1.0;\n"
    "    sa /= 16.0;\n"
    "    vec4 shadow = vec4(uShadowColor.rgb, uShadowColor.a * sa);\n"
    "    finalColor = mix(shadow, texColor, texColor.a);\n"
    "  }\n"
    "  if (uRadius > 0.0) {\n"
    "    vec2 halfSize = uSize * 0.5;\n"
    "    vec2 p = (vUV - 0.5) * uSize;\n"
    "    float dist = sdRoundRect(p, halfSize, uRadius);\n"
    "    float alpha = 1.0 - smoothstep(-1.0, 1.0, dist);\n"
    "    gl_FragColor = vec4(finalColor.rgb, finalColor.a * alpha);\n"
    "  } else {\n"
    "    gl_FragColor = finalColor;\n"
    "  }\n"
    "}\n";

#else // Desktop OpenGL

const char *vs_color_src =
    "#version 110\n"
    "attribute vec2 aPos;\n"
    "attribute vec4 aColor;\n"
    "attribute vec2 aUV;\n"
    "uniform mat4 uProj;\n"
    "uniform mat4 uModel;\n"
    "varying vec4 vColor;\n"
    "varying vec2 vUV;\n"
    "void main(){ vColor=aColor; vUV=aUV; gl_Position=uProj*uModel*vec4(aPos,0.0,1.0); }\n";

const char *fs_color_src =
    "#version 110\n"
    "varying vec4 vColor;\n"
    "varying vec2 vUV;\n"
    "uniform vec2 uSize;\n"
    "uniform float uRadius;\n"
    "uniform float uBlur;\n"
    "uniform float uInvert;\n"
    "uniform int uGradType;\n"
    "uniform vec4 uGradC1;\n"
    "uniform vec4 uGradC2;\n"
    "uniform vec4 uGradC3;\n"
    "uniform vec4 uGradC4;\n"
    "uniform float uGradS1;\n"
    "uniform float uGradS2;\n"
    "uniform float uGradS3;\n"
    "uniform float uGradS4;\n"
    "uniform int uGradCount;\n"
    "uniform float uGradAngle;\n"
    "uniform float uBorderWidth;\n"
    "float sdRoundRect(vec2 p, vec2 b, float r) {\n"
    "  vec2 d = abs(p) - b + vec2(r);\n"
    "  return min(max(d.x, d.y), 0.0) + length(max(d, 0.0)) - r;\n"
    "}\n"
    "vec4 gradient_color(float t) {\n"
    "  if (uGradCount <= 2) return mix(uGradC1, uGradC2, clamp((t - uGradS1) / (uGradS2 - uGradS1), 0.0, 1.0));\n"
    "  if (t <= uGradS2) return mix(uGradC1, uGradC2, clamp((t - uGradS1) / (uGradS2 - uGradS1), 0.0, 1.0));\n"
    "  if (uGradCount == 3) return mix(uGradC2, uGradC3, clamp((t - uGradS2) / (uGradS3 - uGradS2), 0.0, 1.0));\n"
    "  if (t <= uGradS3) return mix(uGradC2, uGradC3, clamp((t - uGradS2) / (uGradS3 - uGradS2), 0.0, 1.0));\n"
    "  return mix(uGradC3, uGradC4, clamp((t - uGradS3) / (uGradS4 - uGradS3), 0.0, 1.0));\n"
    "}\n"
    "void main() {\n"
    "  vec2 halfSize = uSize * 0.5;\n"
    "  vec2 p = (vUV - 0.5) * uSize;\n"
    "  float dist = sdRoundRect(p, halfSize, uRadius);\n"
    "  float alpha = 0.0;\n"
    "  if (uBorderWidth > 0.0) {\n"
    "    vec2 innerHalf = halfSize - vec2(uBorderWidth);\n"
    "    float innerRadius = max(0.0, uRadius - uBorderWidth);\n"
    "    float innerDist = sdRoundRect(p, innerHalf, innerRadius);\n"
    "    float outerAlpha = 1.0 - smoothstep(-1.0, 1.0, dist);\n"
    "    float innerAlpha = 1.0 - smoothstep(-1.0, 1.0, innerDist);\n"
    "    alpha = outerAlpha - innerAlpha;\n"
    "  } else if (uBlur > 0.1) {\n"
    "    alpha = 1.0 - smoothstep(-uBlur * 0.5, uBlur * 1.5, dist);\n"
    "  } else {\n"
    "    alpha = 1.0 - smoothstep(-1.0, 1.0, dist);\n"
    "  }\n"
    "  vec4 finalColor = vColor;\n"
    "  if (uGradType == 1) {\n"
    "    float rad = (90.0 - uGradAngle) * 0.01745329;\n"
    "    vec2 dir = vec2(cos(rad), -sin(rad));\n"
    "    float t = dot(vUV - 0.5, dir) + 0.5;\n"
    "    finalColor = gradient_color(clamp(t, 0.0, 1.0));\n"
    "  } else if (uGradType == 2) {\n"
    "    float t = length(vUV - 0.5) * 2.0;\n"
    "    finalColor = gradient_color(clamp(t, 0.0, 1.0));\n"
    "  }\n"
    "  vec3 rgb = mix(finalColor.rgb, 1.0 - finalColor.rgb, uInvert);\n"
    "  gl_FragColor = vec4(rgb, finalColor.a * alpha);\n"
    "}\n";

const char *vs_text_src =
    "#version 110\n"
    "attribute vec2 aPos;\n"
    "attribute vec2 aUV;\n"
    "attribute vec4 aColor;\n"
    "uniform mat4 uProj;\n"
    "uniform mat4 uModel;\n"
    "varying vec2 vUV;\n"
    "varying vec4 vColor;\n"
    "void main(){ vUV=aUV; vColor=aColor; gl_Position=uProj*uModel*vec4(aPos,0.0,1.0); }\n";

const char *fs_text_src =
    "#version 110\n"
    "uniform sampler2D uTex;\n"
    "uniform float uBlur;\n"
    "uniform float uInvert;\n"
    "varying vec2 vUV;\n"
    "varying vec4 vColor;\n"
    "void main() {\n"
    "  float a = texture2D(uTex, vUV).a;\n"
    "  if (uBlur > 0.1) {\n"
    "    float o = uBlur * 0.0015;\n"
    "    float sum = a * 4.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(o, 0.0)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV - vec2(o, 0.0)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(0.0, o)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV - vec2(0.0, o)).a * 2.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(o, o)).a * 1.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(o, -o)).a * 1.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(-o, o)).a * 1.0;\n"
    "    sum += texture2D(uTex, vUV + vec2(-o, -o)).a * 1.0;\n"
    "    a = sum / 16.0;\n"
    "  }\n"
    "  vec3 color = mix(vColor.rgb, 1.0 - vColor.rgb, uInvert);\n"
    "  gl_FragColor = vec4(color, vColor.a * a);\n"
    "}\n";

const char *vs_image_src =
    "#version 110\n"
    "attribute vec2 aPos;\n"
    "attribute vec2 aUV;\n"
    "uniform mat4 uProj;\n"
    "uniform mat4 uModel;\n"
    "varying vec2 vUV;\n"
    "void main(){ vUV=aUV; gl_Position=uProj*uModel*vec4(aPos,0.0,1.0); }\n";

const char *fs_image_src =
    "#version 110\n"
    "uniform sampler2D uTex;\n"
    "uniform vec2 uSize;\n"
    "uniform float uRadius;\n"
    "uniform vec2 uShadowOffset;\n"
    "uniform float uShadowBlur;\n"
    "uniform vec4 uShadowColor;\n"
    "varying vec2 vUV;\n"
    "float sdRoundRect(vec2 p, vec2 b, float r) {\n"
    "  vec2 d = abs(p) - b + vec2(r);\n"
    "  return min(max(d.x, d.y), 0.0) + length(max(d, 0.0)) - r;\n"
    "}\n"
    "float sampleAlpha(vec2 uv) {\n"
    "  return texture2D(uTex, uv).a;\n"
    "}\n"
    "void main() {\n"
    "  vec4 texColor = texture2D(uTex, vUV);\n"
    "  vec4 finalColor = texColor;\n"
    "  if (uShadowBlur > 0.0 || uShadowOffset.x != 0.0 || uShadowOffset.y != 0.0) {\n"
    "    float o = uShadowBlur * 0.003;\n"
    "    vec2 suv = vUV - uShadowOffset;\n"
    "    float sa = sampleAlpha(suv) * 4.0;\n"
    "    sa += sampleAlpha(suv + vec2(o, 0.0)) * 2.0;\n"
    "    sa += sampleAlpha(suv - vec2(o, 0.0)) * 2.0;\n"
    "    sa += sampleAlpha(suv + vec2(0.0, o)) * 2.0;\n"
    "    sa += sampleAlpha(suv - vec2(0.0, o)) * 2.0;\n"
    "    sa += sampleAlpha(suv + vec2(o, o)) * 1.0;\n"
    "    sa += sampleAlpha(suv + vec2(o, -o)) * 1.0;\n"
    "    sa += sampleAlpha(suv + vec2(-o, o)) * 1.0;\n"
    "    sa += sampleAlpha(suv + vec2(-o, -o)) * 1.0;\n"
    "    sa /= 16.0;\n"
    "    vec4 shadow = vec4(uShadowColor.rgb, uShadowColor.a * sa);\n"
    "    finalColor = mix(shadow, texColor, texColor.a);\n"
    "  }\n"
    "  if (uRadius > 0.0) {\n"
    "    vec2 halfSize = uSize * 0.5;\n"
    "    vec2 p = (vUV - 0.5) * uSize;\n"
    "    float dist = sdRoundRect(p, halfSize, uRadius);\n"
    "    float alpha = 1.0 - smoothstep(-1.0, 1.0, dist);\n"
    "    gl_FragColor = vec4(finalColor.rgb, finalColor.a * alpha);\n"
    "  } else {\n"
    "    gl_FragColor = finalColor;\n"
    "  }\n"
    "}\n";

#endif // WESTON_PLATFORM

} // namespace linweb
